name: Ty
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ty-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.72.2
          environments: lint
          activate-environment: false
          locked: true
      # Type check the library with the lint Pixi environment.
      - run: pixi run -e lint ty
